-- DAO_DML
-- MEMBER
-- 1. 회원가입시 중복확인 
SELECT * FROM MEMBER WHERE CID = 'aaa';
-- 2. 회원가입 
INSERT INTO MEMBER(CID, CPW, CNAME, CEMAIL, IMAGE, CBIRTH, CADDRESS)
    VALUES('aaa','111','홍길동','hong@co.kr','100.jpg','1995-05-31','서울 구로구');
    
INSERT INTO MEMBER(CID, CPW, CNAME, CEMAIL, IMAGE, CBIRTH, CADDRESS)
    VALUES('bbb','111','김길동','kim@co.kr','100.jpg','1995-05-25','서울 강남구');
    
INSERT INTO MEMBER(CID, CPW, CNAME, CEMAIL, IMAGE, CBIRTH, CADDRESS)
    VALUES('ccc','111','김길동','kim@co.kr','100.jpg','1995-05-25','서울 강남구');
-- 3. 로그인  (ID, PW)로
SELECT * FROM MEMBER WHERE CID='aaa' AND CPW='111'; 

-- 4. CID로 DTO 가져오기
SELECT * FROM MEMBER WHERE CID='aaa';

-- 5. 회원정보 수정 
UPDATE MEMBER SET   CPW='111',
                    CNAME='홍홍홍',
                    CEMAIL = 'GG@G.COM',
                    CADDRESS = '부산',
                    CBIRTH = '1999-12-12'
                    WHERE CID ='bbb';
    SELECT * FROM MEMBER;

-- 6. 회원 리스트 보기 
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM MEMBER ORDER BY CID)A) WHERE RN BETWEEN 1 AND 2;
-- 7. 등록된 회원수 
SELECT COUNT(*) CNT FROM MEMBER;

-- MANAGER
-- 1. 관리자 등록(ID,PW)
INSERT INTO MANAGER(MID, MPW,MNAME) VALUES('ggg','222','배수지');
INSERT INTO MANAGER(MID, MPW,MNAME) VALUES('fff','222','강수지');
SELECT * FROM MANAGER;
-- 2. 관리자 로그인(ID,PW) 
SELECT * FROM MANAGER WHERE MID='ggg' AND MPW='222';

-- FILEBOARD(글쓰기 글 목록 글 삭제 글 수정)

SELECT FB.*,

    NVL((SELECT MNAME FROM FILEBOARD F, MEMBER M WHERE F.WRITERID=M.MID AND F.FID=FB.FID),

        (SELECT ANAME FROM FILEBOARD F, MANAGER A WHERE F.WRITERID=A.AID AND F.FID=FB.FID)) WRITERNAME   

    FROM FILEBOARD FB ORDER BY FREF DESC, FSTEP; -- 서브쿼리에 들어갈 inline view

SELECT *

    FROM (SELECT ROWNUM RN, A.*

        FROM (SELECT FB.*,

            NVL((SELECT MNAME FROM FILEBOARD F, MEMBER M WHERE F.WRITERID=M.MID AND F.FID=FB.FID),

            (SELECT ANAME FROM FILEBOARD F, ADMIN A WHERE F.WRITERID=A.AID AND F.FID=FB.FID)) WRITERNAME   

            FROM FILEBOARD FB ORDER BY FREF DESC, FSTEP) A)

    WHERE RN BETWEEN 2 AND 3; -- DAO에 들어갈 쿼리




-- 1. 글목록
SELECT * FROM (SELECT ROWNUM RN, FNUM, CID||MID ID, FTITLE, FHIT, FRDATE, FIP FROM 
(SELECT * FROM FILEBOARD ORDER BY FREF DESC, FRE_STEP)) WHERE RN BETWEEN 2 AND 3;

-- 2. 등록된 글 수 
SELECT COUNT(*)TOCNT FROM FILEBOARD;

-- 3. 원글쓰기 (원글은 고객만)
INSERT INTO FILEBOARD (FNUM, CID, FTITLE, FCONTENT, FFILENAME, FHIT,FIP,FREF, FRE_STEP, FRE_LEVEL )
    VALUES(FILE_SEQ.NEXTVAL, 'aaa','글1','본문1',NULL,'0','126.12.12.1',FILE_SEQ.CURRVAL,0,0);
INSERT INTO FILEBOARD (FNUM, CID, FTITLE, FCONTENT, FFILENAME, FHIT,FIP,FREF, FRE_STEP, FRE_LEVEL )
    VALUES(FILE_SEQ.NEXTVAL, 'aaa','글2','본문2',NULL,'0','126.12.12.1',FILE_SEQ.CURRVAL,0,0);
    INSERT INTO FILEBOARD (FNUM, CID, FTITLE, FCONTENT, FFILENAME, FHIT,FIP,FREF, FRE_STEP, FRE_LEVEL )
    VALUES(FILE_SEQ.NEXTVAL, 'bbb','글1','본문1',NULL,'0','126.12.12.1',FILE_SEQ.CURRVAL,0,0);
    SELECT * FROM FILEBOARD;

-- 4. 답변글 쓰기 전 STEPA;
UPDATE FILEBOARD SET FRE_STEP = FRE_STEP+1 WHERE FREF=5 AND FRE_STEP>0;

-- 5. 답변글 쓰기 (답변은 관리자만)
INSERT INTO FILEBOARD(FNUM, MID, FTITLE, FCONTENT, FFILENAME, FHIT, FIP, FREF, FRE_STEP, FRE_LEVEL)
VALUES(FILE_SEQ.NEXTVAL,'ggg','글1-1','답',NULL,'1','192.120.10.20','1','1','1');

-- 6. 글 상세보기 (FNUM으로 DTO가져오기)
SELECT * FROM FILEBOARD WHERE FNUM=3;

-- 7. 조회수 올리기
UPDATE FILEBOARD SET FHIT = FHIT +1 WHERE FNUM=1;

-- 8. 글 수정하기
UPDATE FILEBOARD SET FTITLE ='수정된 제목',
                     FCONTENT ='수정된 본문',
                     FFILENAME = NULL,
                     FIP = '192.168.10.30' --수정된 아이피는 자동적으로 들어가는 걸로
                     WHERE FNUM=1;
-- 9. 글 삭제하기 
DELETE FROM FILEBOARD WHERE FNUM=1 AND FPW='111';
COMMIT;