-- SEQUENCE & TABLE DROP / CREATE
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP SEQUENCE BOOK_SQ;

CREATE TABLE MEMBER(
    MID     VARCHAR2(100) PRIMARY KEY,
    MPW     VARCHAR2(100) NOT NULL,
    MNAME   VARCHAR2(100) NOT NULL,
    MMAIL   VARCHAR2(100) NOT NULL,
    MPOST   VARCHAR2(100), -- 우편번호
    MADDR   VARCHAR2(100)  -- 주소
);

CREATE SEQUENCE BOOK_SQ MAXVALUE 99999999 NOCYCLE NOCACHE;
CREATE TABLE BOOK(
    BNUM    NUMBER(8) PRIMARY KEY,
    BTITLE  VARCHAR2(100) NOT NULL,
    BWRITER VARCHAR2(100) NOT NULL,
    BRDATE  DATE DEFAULT SYSDATE NOT NULL,
    BIMG1   VARCHAR2(1000) DEFAULT 'noImg.png' NOT NULL,
    BIMG2   VARCHAR2(1000) DEFAULT 'noImg.png' NOT NULL,
    BINFO   VARCHAR2(4000) 
);
-- DUMMY DATA INSERT 

INSERT INTO MEMBER VALUES('aaa','1','홍길동','hong@naver.com','12345','서울');
INSERT INTO BOOK VALUES (BOOK_SQ.NEXTVAL, 'SPRING', '김작가', SYSDATE, 'noImg.png','noImg.png','스프링개념서');
INSERT INTO BOOK (BNUM, BTITLE, BWRITER,BRDATE, BIMG1, BINFO)
VALUES (BOOK_SQ.NEXTVAL, 'SPRING', '김작가', SYSDATE, 'noImg.png','스프링개념서');
INSERT INTO BOOK (BNUM, BTITLE, BWRITER,BRDATE, BIMG2, BINFO)
VALUES (BOOK_SQ.NEXTVAL, 'ORACLE', '박제이', SYSDATE, 'noImg.png','SQL개념서');
INSERT INTO BOOK (BNUM, BTITLE, BWRITER,BRDATE,BINFO)
VALUES (BOOK_SQ.NEXTVAL, 'JAVA', '김작가', SYSDATE,'자바개념서');

SELECT * FROM MEMBER;
SELECT * FROM BOOK;
commit;
