-- scott2로 들어와 딕셔너리 뷰 확인
SHOW USER;
SELECT * FROM USER_TABLES; -- SCOTT2가 가지고 있는 테이블 
SELECT * FROM ALL_TABLES;  -- SCOTT2가 접근가능한 테이블 
SELECT * FROM ALL_TABLES WHERE TABLE_NAME IN ('DEPT','EMP');

--DB의 권한을 가진 사람(SCOTT)이 SCOTT2에게 권한을 부여 해줬기 때문에 가능 
SELECT * FROM SCOTT.EMP;
SELECT * FROM SCOTT.DEPT;
SELECT * FROM SCOTT.EMP E, SCOTT.DEPT D WHERE E.DEPTNO=D.DEPTNO;
EXIT;





