-- ==============================문제 2번===========================
-- 테이블 및 시퀀스 지우기 
DROP TABLE CUS_LEVEL;
DROP TABLE CUSTOMER;
DROP SEQUENCE CUS_SQ;

-- CUS_LEVEL 테이블 생성 
CREATE TABLE CUS_LEVEL(
    LEVELNO     NUMBER(3) PRIMARY KEY,
    LEVELNAME   VARCHAR2(10) NOT NULL);
SELECT * FROM CUS_LEVEL;
COMMIT;
-- CUS_SQ 시퀀스 생성 
CREATE SEQUENCE CUS_SQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
COMMIT;
-- CUSTOMER 테이블 생성     
CREATE TABLE CUSTOMER(
    CNO         NUMBER(4) PRIMARY KEY,
    CNAME       VARCHAR(50) NOT NULL,
    JOINDATE    DATE    DEFAULT SYSDATE,
    PHONE       VARCHAR(20) UNIQUE,
    POINT       NUMBER(10),
    LEVELNO     NUMBER(3) REFERENCES CUS_LEVEL(LEVELNO)
);
SELECT * FROM CUSTOMER;
COMMIT;

-- CUS_LEVEL INSERT 
INSERT INTO CUS_LEVEL VALUES (1, 'VVIP');
INSERT INTO CUS_LEVEL VALUES (2, 'VIP');
INSERT INTO CUS_LEVEL VALUES (3, 'NORMAL');
INSERT INTO CUS_LEVEL VALUES (4, 'BLACK');
SELECT * FROM CUS_LEVEL;
COMMIT;

-- CUSTOMER INSERT
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL,'홍길동','22/03/10','010-9999-9999',0,1);
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL,'이철수','22/04/19','010-8888-8888',NULL,2);
SELECT * FROM CUSTOMER;
COMMIT;

-- 출력
SELECT CNO, CNAME, TO_CHAR(JOINDATE,'YYYY-MM-DD'),PHONE,POINT,LEVELNAME
FROM CUSTOMER C , CUS_LEVEL L
WHERE C.LEVELNO=L.LEVELNO;
COMMIT;



























